node {
    stage('Clone') {
        git branch: 'main',
        url: 'https://github.com/eoastafurov/sber_pdris.git'
    }

    stage('mv') {
        sh 'cd Lab3/app'
    }

    stage('Build') {
        sh 'mvn clean package'
    }
}