node {
    stage('Clone') {
        git branch: 'main',
        url: 'https://github.com/eoastafurov/sber_pdris.git'
    }

    stage('Build') {
        sh 'mv ./Lab3/app/* .'
        sh 'mvn clean package'
    }
}