---

- name: json-person
  hosts: all
  become: no
  
  tasks:
  - name: create dir
    file:
      path: /home/mftiedu/astafurovevgeny/json-person
      state: directory

  - name: cp files to dir
    copy:
      src: ./target/app-1.0-SNAPSHOT.jar
      dest: /home/mftiedu/astafurovevgeny/json-person

  - name: cp json files for tests
    copy:
      src: ./individual.json
      dest: /home/mftiedu/astafurovevgeny/json-person

  - name: cp json files for tests1
    copy:
      src: ./holding.json
      dest: /home/mftiedu/astafurovevgeny/json-person

  - name: cp json files for tests1
    copy:
      src: ./legal_entity.json
      dest: /home/mftiedu/astafurovevgeny/json-person

  - name: deploy jar
    become: yes
    shell: cd "/home/mftiedu/astafurovevgeny/json-person" && nohup java -jar app-1.0-SNAPSHOT.jar &
      
...